name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    # The required ruby version is mentioned in '.ruby-version'
    - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0

    - name: ci/setup-fastlane-dependencies
      shell: bash
      run: |
        echo "::group::setup-fastlane-dependencies"
        bundle install
        echo "::endgroup::"
      working-directory: ./fastlane

    - name: Cache Ruby gems
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: ci/prepare-node-deps
      uses: ./.github/actions/prepare-node-deps
